USE BD_FAZENDA;

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'Cliente')
BEGIN
    PRINT 'A tabela já existe.'
END
ELSE
BEGIN
	CREATE TABLE Cliente 
	(
		  Id INT NOT NULL PRIMARY KEY IDENTITY,
		  NomeCliente VARCHAR(100) NOT NULL,
		  CPF VARCHAR(15) NOT NULL,
		  Email VARCHAR(50) NOT NULL,
		  Ativo BIT DEFAULT 1,
		  DataCriacao DATETIME DEFAULT GETDATE()
	);
	PRINT 'Tabela criada com sucesso.'
END