USE BD_FAZENDA;

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'Usuario')
BEGIN
    PRINT 'A tabela já existe.'
END
ELSE
BEGIN
	-- Criação da tabela Usuario
	CREATE TABLE Usuario (
		Id INT PRIMARY KEY IDENTITY(1,1),
		Fk_Perfil INT NOT NULL,
		Nome NVARCHAR(100) NOT NULL,
		Cep NVARCHAR(15) NOT NULL,
		Endereco NVARCHAR(100) NOT NULL,
		Complemento NVARCHAR(50) NOT NULL,
		Numero NVARCHAR(10) NOT NULL,
		Bairro NVARCHAR(100) NOT NULL,
		UF NVARCHAR(2) NOT NULL,		
		Email NVARCHAR(100) NOT NULL UNIQUE,
		Senha NVARCHAR(20) NOT NULL,
		Ativo BIT DEFAULT 1,
		DataCriacao DATETIME DEFAULT GETDATE()
		CONSTRAINT FK_Perfil FOREIGN KEY (Id)
	    REFERENCES Perfil(Id)		
	);
	PRINT 'Tabela criada com sucesso.'
END