USE BD_FAZENDA;

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'Produto')
BEGIN
    PRINT 'A tabela já existe.'
END
ELSE
BEGIN
	CREATE TABLE Produto
	(
		Id INT NOT NULL PRIMARY KEY IDENTITY,
		Produto VARCHAR(50) NOT NULL,
		Quantidade INT NOT NULL,
		Preco DECIMAL(10, 2) NOT NULL,
		Status BIT DEFAULT 1,
		DataCriacao DATETIME DEFAULT GETDATE()
	);
	PRINT 'Tabela criada com sucesso.'
END